### ISSUE TITLE
Support for HACS

### ISSUE THREAD

**Issue by inifinityandbeyond** [mmillmor/home-assistant-components#1]
Hi.  As a novice, to home assistant, I would really like to take advantage of your development for the Heatmiser Netmonitor, but I'm really struggling.  I've copied the files to my HA, but then nothing happens.  Any chance you could make your project compatible with HACS, as shown in the following video:
 
https://www.youtube.com/watch?v=xpqUe-TkO70

At the moment, HACS tells me the project is not compatible.

**Comment by inifinityandbeyond** [comment]
Also, the code doesn't seem to want to work with HA running via Synology.  Please find attached the HA log file.

[homeassistant.log](https://github.com/mmillmor/home-assistant-components/files/15265004/homeassistant.log)

**Comment by mmillmor** [comment]
Good suggestion about HACS. I have added it at https://github.com/mmillmor/heatmiser_netmonitor

As for Synology, I can't help with that I'm afraid
