### ISSUE TITLE
Is there a way to setting Holidays 

### ISSUE THREAD

**Issue by danielTinkiel** [mmillmor/home-assistant-components#2]
I have my old Netmonitor working on Home Assistant. mmillmor : congratulations! you have done a Fantastic job!
I failed to find a way to set holidays. To be able to set the system time and BST would be a plus. If somebody knows the way to access these, I will be grateful. Thanks

**Comment by mmillmor** [comment]
Hi Daniel, I'm glad you like it.

There is a service call to set the system time (Heatmiser NetMonitor: Set System Time). It sets it to the current time of your home automation system. You could call it daily for example.

For setting holidays, I don't have anything to set that. Perhaps set a timer to turn each stat off and another to turn each one on?

**Comment by danielTinkiel** [comment]
Hi Martin,
Thank you for responding. I will look for the service that you mention and call it oncer every so and then, may be every two weeks. The deviation of time in my system, even though it is supposed to get it from the internet time service, is not that bad but going off if you allow it for a long time with no correction.
For the holidays, I guess that I will have to do something else. The timer is one good possibility.

Many thanks again.

Kind regards,
Daniel


Daniel Tinkiel
10 King Edward Park,
Bray, Co. Wicklow, A98EC52
Ireland
+353 86 382 3929

________________________________

**Comment by mmillmor** [comment]
I liked the idea of setting the holidays, so it has been added now. This repo is obsolete now, and the new code is at https://github.com/mmillmor/heatmiser_netmonitor, which you can install using HACS

**Comment by danielTinkiel** [comment]
Hi Martin,
It is great to know that you have updated it. I am relatively new in HA, and I miserably failed to try to update your previous integration that I currently have installed. Would you please indicate me the way to update it?
Many thanks.
Kind regards,
Daniel


Daniel Tinkiel
10 King Edward Park,
Bray, Co. Wicklow, A98EC52
Ireland
+353 86 382 3929

________________________________

**Comment by danielTinkiel** [comment]
Hi Martin,
Thank you very much for updating the integration with these useful functionality. I hace proceeded to update it in my system., but I don't know how to invoke it. I thought that new entities would be available to be included in the corresponding dashboard but I didn't find them. I will appreciate if you please let me know how to invoke them.  Thanks again.
Kind regards,
Daniel



Sent from my Galaxy


-------- Original message --------
From: mmillmor ***@***.***>
Date: 04/12/2024 20:32 (GMT+00:00)
To: mmillmor/home-assistant-components ***@***.***>
Cc: danielTinkiel ***@***.***>, Author ***@***.***>
Subject: Re: [mmillmor/home-assistant-components] Is there a way to setting Holidays (Issue #2)


I liked the idea of setting the holidays, so it has been added now. This repo is obsolete now, and the new code is at https://github.com/mmillmor/heatmiser_netmonitor, which you can install using HACS

**Comment by mmillmor** [comment]
If you want to run it when you push a button (as opposed to on a timer or
an event), all you need to do is create a Helper Button, add an automation
which runs the service when it's toggled

**Comment by danielTinkiel** [comment]
Hi Martin,
Sorry to be a pest on this. My knowledge of HA is just incipient and I don't know how to use the new functionality at all in any way being an event or timer as you mentioned. If you just give me some hints I will pick it up.  I intend to replace the functionality provided by the original Android app which is now not able to use in more modern Android versions for a reason which only Google Play know. So, I used your integration and managed to have the system managed from HA. So, please tell me how to put the system in holidays mode in any way as you originally planned to.  Many thanks.
Daniel



Sent from my Galaxy


-------- Original message --------
From: mmillmor ***@***.***>
Date: 09/12/2024 20:00 (GMT+00:00)
To: mmillmor/home-assistant-components ***@***.***>
Cc: danielTinkiel ***@***.***>, Author ***@***.***>
Subject: Re: [mmillmor/home-assistant-components] Is there a way to setting Holidays (Issue #2)


If you want to run it when you push a button (as opposed to on a timer or
an event), all you need to do is create a Helper Button, add an automation
which runs the service when it's toggled

**Comment by mmillmor** [comment]
See https://github.com/mmillmor/heatmiser_netmonitor/blob/main/README.md for some examples

**Comment by danielTinkiel** [comment]
Thank you Martin.
Regards,
Daniel

Daniel Tinkiel
10 King Edward Park,
Bray, Co. Wicklow, A98EC52
Ireland
+353 86 382 3929

________________________________
