### ISSUE TITLE
Home/Away 

### ISSUE THREAD

**Issue by KeithL52** [mmillmor/home-assistant-components#3]
Have you thought about adding the ability to set Home/Away ?

Then you could do away with the horrible slow Heatmiser app

PS Another small issue, the "Documentation" link in the integration is wrong https://www.home-assistant.io/integrations/heatmiser_netmonitor

**Comment by mmillmor** [comment]
I liked the idea of setting the holidays, so it has been added now. This repo is obsolete now, and the new code is at https://github.com/mmillmor/heatmiser_netmonitor, which you can install using HACS
